### ISSUE TITLE
After upgrade Dimmers not showing

### ISSUE THREAD

**Issue by rtjdamen** [robmarkcole/Hue-sensors-HASS#137]
After installing the latest version with the new structure I can read motion sensors, the dimmer switches however are not showing up. Am I doing something wrong?

**Comment by robmarkcole** [comment]
Which version of what? HA or this CC?

**Comment by rtjdamen** [comment]
Latest of this CC and the latest HA 0.92.0

**Comment by robmarkcole** [comment]
I need to setup hue to check, unfortunately I am moving home this week

**Comment by rtjdamen** [comment]
Ok, i will try an older version later today to see if that is still working

**Comment by robmarkcole** [comment]
OK I just set it up at my parents house and all working. What is your config?

**Comment by alexthomsen** [comment]
I have the same problem. The dimmers stoppede working after an hue bridge update.

**Comment by rtjdamen** [comment]
I miss the remote's they will not showup, they did in the past. I tried the CC files from January but have the same issue. Seems like Alex Thomsen is Right, its broken after an huebridge update.

**Comment by claytonjn** [comment]
My hub (model BSB002) is on firmware 1931140060 as of 4/2/19. The Friends of Hue remotes are all working perfectly. The people who suspect a firmware update is causing an issue should really post their firmware version to get an idea if that's at all related. In general, however, a firmware update shouldn't break this component. This component talks to the Hue bridge through a very well documented, official AP - it would be very unlikely that Hue would make any significant breaking changes to the API and if they did there would be plenty of warning. The whole point of an API is so that there's a layer between the hardware and software such that firmware updates, etc can occur without breaking anything.

**Comment by rtjdamen** [comment]
I am using 1931140050

**Comment by rtjdamen** [comment]
I agree Claytonjn, it is unlikely but there should be a reason that the hue remotes are not working for some of us.

**Comment by alexthomsen** [comment]
Hi again, im on version 1931069120, the newest one i can update to.

**Comment by alexthomsen** [comment]
im confused, found this in my homeassistant log. When the remotes didnt work yesterday, i have also updated homeassistant to the newest version. I hoped that will fix it.

2019-04-28 12:32:01 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform hue
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 122, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 87, in async_create_setup_task
    None, platform.setup_platform, hass, platform_config,
AttributeError: module 'homeassistant.components.hue.sensor' has no attribute 'setup_platform'

**Comment by claytonjn** [comment]
> 2019-04-28 12:32:01 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform hue
> Traceback (most recent call last):
> File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 122, in _async_setup_platform
> task = async_create_setup_task()
> File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 87, in async_create_setup_task
> None, platform.setup_platform, hass, platform_config,
> AttributeError: module 'homeassistant.components.hue.sensor' has no attribute 'setup_platform'

It looks like your issue is with the official Hue integration, which the huesensor custom component relies on. What does your setup look like in terms of the custom_component folder and your configuration.yaml for both `hue` and `huesensor`?

**Comment by alexthomsen** [comment]
custom_components:
.
- hue
  - binary_sensor.py
  - device_tracker.py
  - __init__.py
  - __pycache__
    - binary_sensor.cpython-37.pyc
    - device_tracker.cpython-37.pyc
    - sensor.cpython-37.pyc
  - sensor.py

And in the configuration.yaml:

binary_sensor:
  - platform: hue

device_tracker:
  - platform hue

sensor:
  - platform: hue

**Comment by alexthomsen** [comment]
hmm, did the sensor changed name to huesensor recently :-) The above setup has been working for several month without issues :-)

**Comment by rtjdamen** [comment]
I use huesensor




On Mon, Apr 29, 2019 at 4:41 PM +0200, "alexthomsen" <notifications@github.com<mailto:notifications@github.com>> wrote:


hmm, did the sensor changed name to huesensor recently :-) The above setup has been working for several month without issues :-)

**Comment by alexthomsen** [comment]
I have changed the configuration and custom_compontent folder to huesensor. The error message disappeared, but there are still no dimming switches.

**Comment by claytonjn** [comment]
> hmm, did the sensor changed name to huesensor recently :-) The above setup has been working for several month without issues :-)

Yes, as of HA ~0.88 custom components can no longer "extend" official integrations, they have to either fully replace them or use a different domain. https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html


> I have changed the configuration and custom_component folder to huesensor. The error message disappeared, but there are still no dimming switches.

Do you have any errors in your logs now?

**Comment by alexthomsen** [comment]
I have no errors in the log. 
I just tried curling the hue bridge and the dimmers show up, but they aren´t picked up by this plugin.

**Comment by rtjdamen** [comment]
i could find this one

Tue Apr 30 2019 10:25:14 GMT+0200 (Midden-Europese zomertijd)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/huesensor/sensor.py", line 155, in update_bridge
    for sensor in bridge.api.sensors.values()
  File "/config/custom_components/huesensor/sensor.py", line 58, in parse_hue_api_response
    data_dict[_key] = parse_zgp(sensor)
  File "/config/custom_components/huesensor/sensor.py", line 70, in parse_zgp
    button = TAP_BUTTONS[press]
KeyError: 0

**Comment by claytonjn** [comment]
@rtjdamen that issue is the same as outlined here: https://github.com/robmarkcole/Hue-sensors-HASS/issues/132

**Comment by alexthomsen** [comment]
I have no pressed my unused tap buttons without any changes. 

Maybe this will help finding the problem:
`"name":"Stue bord kontakt","type":"ZLLSwitch","modelid":"RWL021","manufacturername":"Philips","productname":"Hue dimmer switch","diversityid":"73bbabea-3420-499a-9856-46bf437e119b","swversion":"5.45.1.17846","uniqueid":"00:17:88:01:02:c2:33:fb-02-fc00","capabilities":{"certified":true,"inputs":[{"repeatintervals":[800],"events":[{"buttonevent":1000,"eventtype":"initial_press"},{"buttonevent":1001,"eventtype":"repeat"},{"buttonevent":1002,"eventtype":"short_release"},{"buttonevent":1003,"eventtype":"long_release"}]},{"repeatintervals":[800],"events":[{"buttonevent":2000,"eventtype":"initial_press"},{"buttonevent":2001,"eventtype":"repeat"},{"buttonevent":2002,"eventtype":"short_release"},{"buttonevent":2003,"eventtype":"long_release"}]},{"repeatintervals":[800],"events":[{"buttonevent":3000,"eventtype":"initial_press"},{"buttonevent":3001,"eventtype":"repeat"},{"buttonevent":3002,"eventtype":"short_release"},{"buttonevent":3003,"eventtype":"long_release"}]},{"repeatintervals":[800],"events":[{"buttonevent":4000,"eventtype":"initial_press"},{"buttonevent":4001,"eventtype":"repeat"},{"buttonevent":4002,"eventtype":"short_release"},{"buttonevent":4003,"eventtype":"long_release"}]}]}},"29":{"state":{"buttonevent":1002,"lastupdated":"2019-04-27T17:29:44"},"swupdate":{"state":"noupdates","lastinstall":null},"config":{"on":true,"battery":100,"reachable":true,"pending":[]},`

**Comment by akiaie** [comment]
Hi,
After updating my hassio to 0.92.1 I have the same problem. my motion sensors changed names which i fixed them, but the dimmers don't show up. I copied latest component from here but now I get below error from hassio:
![image](https://user-images.githubusercontent.com/39561169/56978008-1fe11300-6ba9-11e9-8662-7628ce9bc30c.png)
my hue bridge SW: 1931069120

**Comment by purebenwoo** [comment]
Surprisingly mine started working, but I  had to reinstall from the beginning.

---
Ben Woo
+1 (212) 724-1188
On 4/30/2019 9:37:19, akiaie <notifications@github.com> wrote:
Hi,
After updating my hassio to 0.92.1 I have the same problem. my motion sensors changed names which i fixed them, but the dimmers don't show up. I copied latest component from here but now I get below error from hassio:
[image] [https://user-images.githubusercontent.com/39561169/56978008-1fe11300-6ba9-11e9-8662-7628ce9bc30c.png]
my hue bridge SW: 1931069120

**Comment by akiaie** [comment]
mine start working after I copied recent component. thanks

**Comment by alexthomsen** [comment]
Okay im lost, maybe it is not the same issue. Now i have reinstalled the component, but im still struggling.

**Comment by rtjdamen** [comment]
Could it be some cached settings? I had some similar issues with homebridge in the past. Removing some cached settings did the trick there. 
Maybe that explains why a clean install does the trick?

**Comment by wardcoertjens** [comment]
I had the same issue after updating. After reinstalling the custom component with the latest files, dimmers seem to be working now.

**Comment by rtjdamen** [comment]
It seems the hue tab i have was breaking my config.. This is resolved by removing it.

**Comment by alexthomsen** [comment]
I have re pulled my docker image but i kept the configuration files. There was no changes and the dimmers are still missing.

**Comment by rtjdamen** [comment]
Do you have an hue tab?

Met Vriendelijke groet, Best Regards,
Robin Damen
CEO

Virtual Computing BV – isaBEL – VC Healthcare
Laarakkerweg 6A, 5061JR Oisterwijk, The Netherlands
T:  + 31 (0) 13 7110324 | F: + 31 (0) 847 556 730 | M: +31 (0) 6 43 56 16 26 | E: rtjdamen@virtualcomputing.nl<mailto:rtjdamen@virtualcomputing.nl>
Hoe bent u geholpen? How did i help you?
[red_smiley]<http://satifact.virtualcomputing.nl/index.php?rate=1&from=robin&ticketnr=none>[orange_smiley]<http://satifact.virtualcomputing.nl/index.php?rate=2&from=robin&ticketnr=none>[green_smiley]<http://satifact.virtualcomputing.nl/index.php?rate=3&from=robin&ticketnr=none>
*** Dit e-mailbericht is uitsluitend bestemd voor de geadresseerde(n). Wilt u direct contact met Virtual Computing opnemen indien deze e-mail door een vergissing bij u is terechtgekomen? Virtual Computing verzoekt u in dat geval de gehele e-mail te vernietigen, de inhoud ervan niet te gebruiken en niet onder derden te verspreiden omdat het bericht vertrouwelijke informatie kan bevatten beschermd door een geheimhoudingsplicht. De inhoud van dit bericht is niet wettelijk bindend voor zover niet bevestigd door brief of fax. Van toepassing zijn de algemene voorwaarden zoals gedeponeerd bij de Kamer van Koophandel Brabant onder nummer  52527468.
Deze e-mail, inclusief gegevensbestanden die daarbij verzonden zijn, is naar mening van Virtual Computing vrij van virussen. Virtual Computing adviseert u echter de inhoud c.q. de bestanden voor gebruik nogmaals op de aanwezigheid van virussen te onderzoeken en indien nodig de noodzakelijke maatregelen te nemen om vervuiling van uw software, bestanden of computer(s) te voorkomen. Virtual Computing kan niet aansprakelijk worden gesteld voor de door het gebruik van de door ons verstrekte bestanden ontstane schade. ***

Van: alexthomsen <notifications@github.com>
Verzonden: donderdag 2 mei 2019 16:27
Aan: robmarkcole/Hue-sensors-HASS <Hue-sensors-HASS@noreply.github.com>
CC: Robin Damen - Virtual Computing BV <rtjdamen@virtualcomputing.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [robmarkcole/Hue-sensors-HASS] After upgrade Dimmers not showing (#137)


I have re pulled my docker image but i kept the configuration files. There was no changes and the dimmers are still missing.

**Comment by alexthomsen** [comment]
I have 2 unused, but i have removed them from the hue app.

**Comment by alexthomsen** [comment]
OMG now it´s working. It was a combination of me being stupid and some cache. I had rename the sensor from hue to huesensor, delete the __pycache__ from the module and not download the files from github with wget. When i looked at my files i had a website :-)

**Comment by robmarkcole** [comment]
It sounds like the issue is cached files which required removal?

**Comment by robmarkcole** [comment]
Been quiet for a while, closing
