### ISSUE TITLE
Hue integration is unusable

### ISSUE THREAD

**Issue by warcanoid** [robmarkcole/Hue-sensors-HASS#138]
Hue integration is unusable on 0.92.x because it has delay 5seconds when reporting motion. @robmarkcole do you have a fix or can you help them out? I have migrated back to your component because it is reliable and it works.

**Comment by fondberg** [comment]
I experience the same after updating. Also I see some problems at startup because the component tries to read from the `hue` component before it is initialized.
I will try an older version and see if the delay is reduced

```
2019-05-05 16:52:06 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform huesensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/config/custom_components/huesensor/binary_sensor.py", line 146, in async_setup_platform
    await data.async_update_info()
  File "/config/custom_components/huesensor/binary_sensor.py", line 203, in async_update_info
    bridges = get_bridges(self.hass)
  File "/config/custom_components/huesensor/binary_sensor.py", line 126, in get_bridges
    for entry in hass.data[hue.DOMAIN].values()
KeyError: 'hue'
```

**Comment by warcanoid** [comment]
Ha 0.92.2 and cc hue 1.0.5 binary_sensor for motion and sensor for wall switces

**Comment by fondberg** [comment]
There is no difference in the code in the binary sensor since 1.0.4. 1.0.5 has been there since a long time.
Can you checkout the latest and compare the binary_sensor.py with the one you have on the HA in custom_component?

**Comment by warcanoid** [comment]
I have the latest files from huesensor. Have you seen this: https://github.com/home-assistant/home-assistant/issues/23502

**Comment by fondberg** [comment]
If you have the latest then I don't understand your statement " I have migrated back to your component because it is reliable and it works."

I will test the native support of hue motion later

**Comment by robmarkcole** [comment]
Please keep issues on this repo to code on this repo. 
I don't have much spare time these days unfortunately.
Thanks
