### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by mf-social** [robmarkcole/Hue-sensors-HASS#15]
Hi,

I've been using this componet for a few weeks without issue.

Today I've added a motion sensor to my setup, and (totally by fluke timing) the hue software has updated on the bridge and a couple of the bulbs.

Restarting HA the hue component now won't start, this is the error:

```
Error while setting up platform hue
Traceback (most recent call last):
  File "/home/hass/srv/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hass/.homeassistant/custom_components/sensor/hue.py", line 27, in setup_platform
    data.update()
  File "/home/hass/srv/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
    result = method(*args, **kwargs)
  File "/home/hass/.homeassistant/custom_components/sensor/hue.py", line 51, in update
    self.data = self.parse_hue_api_response(response.json())
  File "/home/hass/srv/lib/python3.6/site-packages/hue_sensors.py", line 49, in parse_hue_api_response
    data_dict[_key] = parse_zpg(sensor)
  File "/home/hass/srv/lib/python3.6/site-packages/hue_sensors.py", line 99, in parse_zpg
    button = TAP_BUTTONS[press]
KeyError: None
```

I can't say whether it was adding the motion sensor or the update that killed it.  I've waited a few hours before reporting this as an issue in case it was because it was still updating the devices in the background, but they've all been showing as up-to-date for quite a while now.

Any ideas?

**Comment by mf-social** [comment]
Hang on - I've fixed this myself after re-reading the error message.  What I think has happened is this:

When the hub (or possibly the tap) updated it reset the tap and therefore it wasn't showing a last_pressed entry.

I've fixed this by pressing a button on the tap, and then restarting home assistant.

I'm sorry I don't know python so I wouldn't know where to start for a PR to fix this in the component itself, so I'll leave this issue open so somebody can take a look.

**Comment by mf-social** [comment]
#14 may be a similar issue?

**Comment by robmarkcole** [comment]
OK the issue here, is that if HA has been reset and the remote has no data since the reset, then the hue API returns `"buttonevent": null` and currently `hue_sensors` does not handle a null value. I've added this to https://github.com/robmarkcole/Hue-sensors/issues/4

**Comment by robmarkcole** [comment]
This is being dealt with in https://github.com/robmarkcole/Hue-sensors/issues/4
