### ISSUE TITLE
Fix: Error while setting up platform huesensor - KeyError: 'hue'

### ISSUE THREAD

**Issue by JurajNyiri** [robmarkcole/Hue-sensors-HASS#152]
After upgrading the hass bridge to SW: 1932073040, update from 2019-06-08, I started randomly encountering a new issue. At the same time, HASS 0.94.x has been released. Often after restart/start, huesensor would crash and not recover. This affected all domains, binary_sensor, device_tracker, and sensor.

I tried using the master without my fix again with 0.95, encountering the same issue again. 

```
2019-06-27 10:14:58 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform huesensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/config/custom_components/huesensor/binary_sensor.py", line 145, in async_setup_platform
    await data.async_update_info()
  File "/config/custom_components/huesensor/binary_sensor.py", line 202, in async_update_info
    bridges = get_bridges(self.hass)
  File "/config/custom_components/huesensor/binary_sensor.py", line 125, in get_bridges
    for entry in hass.data[hue.DOMAIN].values()
KeyError: 'hue'
2019-06-27 10:15:02 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform huesensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/config/custom_components/huesensor/sensor.py", line 167, in async_setup_platform
    await data.async_update_info()
  File "/config/custom_components/huesensor/sensor.py", line 224, in async_update_info
    bridges = get_bridges(self.hass)
  File "/config/custom_components/huesensor/sensor.py", line 147, in get_bridges
    for entry in hass.data[hue.DOMAIN].values()
KeyError: 'hue'
```

I created a [PR](https://github.com/robmarkcole/Hue-sensors-HASS/pull/144) to fix this. It has been closed, but https://github.com/JurajNyiri/Hue-sensors-HASS/tree/fix_keyerror_hue is still up to date with master, let me know if I should create a new PR.

This issue has been mentioned in community multiple times, for example [here](https://community.home-assistant.io/t/hue-motion-sensors-remotes-custom-component/27176/992).

**Comment by robmarkcole** [comment]
Is this still an issue?

**Comment by JurajNyiri** [comment]
Seems like it has been fixed.
