### ISSUE TITLE
NameError: name 'button' is not defined

### ISSUE THREAD

**Issue by ljmerza** [robmarkcole/Hue-sensors-HASS#203]
```
2020-02-05 11:14:15 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/huesensor/remote.py", line 275, in update_bridge
    for sensor in bridge.api.sensors.values()
  File "/config/custom_components/huesensor/remote.py", line 84, in parse_hue_api_response
    key_value = parse_z3_rotary(sensor)
  File "/config/custom_components/huesensor/remote.py", line 198, in parse_z3_rotary
    "last_button_event": button,
NameError: name 'button' is not defined
```

**Comment by robmarkcole** [comment]
this is fixed in latest release
