### ISSUE TITLE
Error filing up log and stopping HA from restarting

### ISSUE THREAD

**Issue by TheCellMC** [robmarkcole/Hue-sensors-HASS#215]
Hi, first of all, thanks for the amazing work you did on this component 👍 

Unfortunately, I have been running into a few issues for the past week with this component. I am running the latest version. Sometimes, when I restart HA, my log gets filled up with these errors and HA does not start up, forcing me to reboot the server manually.

I have a dozen bulbs, 3 indoor hue sensors, 1 outdoor hue sense, 2 remotes and 1 hue tap.

Do you know what might be going wrong here?

I have already seen a few similar issues with this component which were related to the hue tap. 
 
```
2020-02-13 13:40:23 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 478, in _sock_connect
    sock.connect(address)
BlockingIOError: [Errno 115] Operation in progress

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/huesensor/remote.py", line 227, in update_bridge
    available = await update_api(bridge.api.sensors)
  File "/config/custom_components/huesensor/__init__.py", line 26, in update_api
    await api.update()
  File "/usr/local/lib/python3.7/site-packages/aiohue/api.py", line 12, in update
    raw = await self._request('get', self._path)
  File "/usr/local/lib/python3.7/site-packages/aiohue/bridge.py", line 68, in request
    async with self.websession.request(method, url, json=json) as res:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 945, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 472, in sock_connect
    self._sock_connect(fut, sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 486, in _sock_connect
    self.add_writer(fd, self._sock_connect_cb, fut, sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 338, in add_writer
    self._ensure_fd_no_transport(fd)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 249, in _ensure_fd_no_transport
    f'File descriptor {fd!r} is used by transport '
RuntimeError: File descriptor 35 is used by transport <_SelectorDatagramTransport fd=35 read=polling write=<idle, bufsize=0>>

```

**Comment by robmarkcole** [comment]
That looks like an issue arising from the `hue` integration. Will leave this issue open to see if anyone else can shed some light on it

**Comment by rafuz** [comment]
I am having the same problems in the last hours.
This is the log:

```
Traceback (most recent call last):
  File "/config/custom_components/huesensor/__init__.py", line 22, in update_api
    await api.update()
  File "/usr/local/lib/python3.7/site-packages/aiohue/api.py", line 12, in update
    raw = await self._request('get', self._path)
  File "/usr/local/lib/python3.7/site-packages/aiohue/bridge.py", line 68, in request
    async with self.websession.request(method, url, json=json) as res:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 945, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
    return await fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/huesensor/__init__.py", line 22, in update_api
    await api.update()
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/huesensor/remote.py", line 235, in update_bridge
    available = await update_api(bridge.api.sensors)
  File "/config/custom_components/huesensor/__init__.py", line 24, in update_api
    _LOGGER.debug("Failed to fetch sensors: %s", err)
NameError: name '_LOGGER' is not defined
```

**Comment by robmarkcole** [comment]
Well as you can see this is an error that is also affecting the lights, and results when `update_api` is called and not getting data within the timeout duration. I can fix the ` '_LOGGER' is not defined` by removing it, this is resulting from some annoying import error.

**Comment by robmarkcole** [comment]
Try https://github.com/robmarkcole/Hue-sensors-HASS/releases/tag/2.10

However we need to diagnose why this timeout error has only started occuring recently

**Comment by robmarkcole** [comment]
Ref https://github.com/home-assistant/home-assistant/issues/31807

**Comment by TheCellMC** [comment]
I have updated to the latest version and will keep you updated if this issue occurs again.

I have also been seeing similar behaviour with the built-in Logitech Harmony integration yesterday which seemed to be related to aiohttp.

**Comment by Kugelfang666** [comment]
I'm also having issues with a flooded log: 

https://github.com/home-assistant/home-assistant/issues/32380#

**Comment by balloob** [comment]
This custom integration is a big source of Hue issues. Making a request at 0.1s is hammering the hub, causing it to go unavailable. 

At least if you're using sensor data, use the same data source as Home Assistant. Don't make your own requests on top of it. The data update coordinator is available at `bridge.sensor_manager.coordinator`. You can register for updates and trigger refreshes. Look at the Hue integration on how to pull it into your sensors.

**Comment by robmarkcole** [comment]
Personally I have never had an issue, but I have dropped the scan rate on the custom integration. My wife is giving birth soon so I don't have free time to address this, hopefully someone can step up and help out with the required changes.

**Comment by Kugelfang666** [comment]
thanks for the update

I just updated to the new version which has the lower polling rate (0.5) , I'll give it a spin and report back,

gernerally speaking, having the hue dimmer switches available in HA as sensors for me is a major asset since I'm heavily using them to trigger automation, control devices... Hence, having a "proper" solution would be fantastic.

**Comment by Kugelfang666** [comment]
Also with the reduced poll rate I still get the errors in my brige

**Comment by Mariusthvdb** [comment]
Even with 1sec scan rate this is now causing severe issues I am afraid. Though must admit before the change in the architecture it wasn’t this bad...
Really sorry.
For the record see also this issue on HA repo

https://github.com/home-assistant/core/issues/32380#issuecomment-595428079

**Comment by robmarkcole** [comment]
OK so the only path forward is a re-write to use the same data source as the official integration as https://github.com/robmarkcole/Hue-sensors-HASS/issues/220

**Comment by Mariusthvdb** [comment]
2 things:
Even without the custom integration Hassio is showing hue unavailable. Not only lights, but while I’ve completely integrated all core sensors and binary sensors in favor of the custom integration which I now have disabled, also all sensors show unavailable. I’ve reported this and it raises suspicion something else is faulty in core Ha...

Secondly, rebuilding the CC, why not only add sensors/logic which are not available on the core integration. That way we know nothing spurious or redundant is added.

My 2 cents

**Comment by Kugelfang666** [comment]
I just updated to 2.12. Interestingly im now only finding two errors:

```
ERROR (MainThread) [homeassistant.components.hue.light] Error fetching group data: 
ERROR (MainThread) [homeassistant.components.hue.light] Error fetching light data: 
```

Previously there was also this line which now is disappeared
```
ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: ```

**Comment by Mariusthvdb** [comment]
Still here:

![EC60E54C-AD2C-49AA-BA1C-2E0B540E0762](https://user-images.githubusercontent.com/33354141/76191714-48ca2f80-61e0-11ea-9f1c-48c45bbb4503.png)

**Comment by Mariusthvdb** [comment]
just so you know, refactoring didn't change this at all:

```
2020-03-10 16:08:42 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:08:45 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching light data: 
2020-03-10 16:08:49 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching group data: 
2020-03-10 16:09:20 ERROR (MainThread) [pyhaversion] Timeout error fetching version information from Hassio, 
2020-03-10 16:09:20 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:09:23 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching light data: 
2020-03-10 16:09:42 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:10:00 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:10:04 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching group data: 
2020-03-10 16:10:10 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching light data: 
2020-03-10 16:10:22 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:13:14 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:14:45 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:14:49 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching light data: 
2020-03-10 16:14:50 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching group data: 
2020-03-10 16:15:03 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:17:44 ERROR (MainThread) [homeassistant.helpers.service] Error rendering data template: UndefinedError: 'mappingproxy object' has no attribute 'battery'
2020-03-10 16:20:02 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching light data: 
2020-03-10 16:20:06 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching group data: 
2020-03-10 16:20:18 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:21:00 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:21:12 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data: 
2020-03-10 16:24:07 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching light data: 
2020-03-10 16:24:08 ERROR (MainThread) [homeassistant.components.hue.light] Error fetching group data: 
```

this is with the latest 2.13 refactor
