### ISSUE TITLE
2.13 Log errors when motion sensor triggered.

### ISSUE THREAD

**Issue by Fulch** [robmarkcole/Hue-sensors-HASS#228]
HA 106.6
Native hue integration setup, only using custom component for remotes.
Only entry referencing 'huesensor' in configuration.yaml .
``` yaml
### hue sensors ###
remote:
  - platform: huesensor
    scan_interval: 2
```
Get this pair of errors  each time a motion sensor is activated, the sensors are paired to the hue hub and are working as I would expect. The log time stamps exactly match the 'detect' and 'clear' event times reported in HA.

2020-03-11 11:32:16 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/huesensor/data_manager.py", line 137, in async_update_from_bridges
    self.sensors[dev_id].async_write_ha_state()
KeyError: 'SML_00:17:88:01:03:2b:f8:78-02'
2020-03-11 11:32:31 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/huesensor/data_manager.py", line 137, in async_update_from_bridges
    self.sensors[dev_id].async_write_ha_state()
KeyError: 'SML_00:17:88:01:03:2b:f8:78-02'

 Thanks for looking.

**Comment by azogue** [comment]
Hi @Fulch,

Some things were broken (sorry!) with the last versions. I hope they are fixed with #229. Could you check it before it is released, to be sure?

**Comment by Fulch** [comment]
Hi @azogue,

Have only got one bridge in my setup to test with but am pleased to say no more log errors in response to motion sensor events. Tested my two remotes as well and all looks good!

Thank you very much for such a prompt fix.

**Comment by Kugelfang666** [comment]
Will give it a spin tonight. Just a naive question, how do I deploy a non released version to my system. Typically I’m using HACS to deploy CC to my setup...

**Comment by azogue** [comment]
Hi @Kugelfang666,

> how do I deploy a non released version to my system. Typically I’m using HACS to deploy CC to my setup...

If you have access to your ha host (with SAMBA or any other), you should see the CC files in the `custom_components` folder, so you could download the repo from the unmerged branch in https://github.com/azogue/Hue-sensors-HASS/tree/feature/refactor and replace the files (not sure if it would break HACS for the version handling, though, so use with care)

Maybe @robmarkcole releases it quickly :)

**Comment by Kugelfang666** [comment]
so I just updated to the 2.14 an with that all sensors from both bridges seem to be working. Was your proposed PR part of 2.14?

**Comment by Kugelfang666** [comment]
so I just updated the CC to 2.14 . while I still encounter the errors in the log something has changed: 

```
ERROR (MainThread) [homeassistant.components.hue.light] Error fetching group data: 
ERROR (MainThread) [homeassistant.components.hue.light] Error fetching light data: 
ERROR (MainThread) [homeassistant.components.hue.sensor_base] Error fetching sensor data:
``` 

Error fetching light data: 83x
Error fetching group data: 84x
Error fetching sensor data: 2x

before they always had the same (similar) count...
