### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by GarmFighter** [robmarkcole/Hue-sensors-HASS#27]
Doing as instructed this is what i get.

2018-01-09 23:36:57 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/discovery.py", line 164, in async_load_platform
    hass, component, hass_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 49, in async_setup_component
    return (yield from setup_tasks[domain])
  File "/usr/lib/python3.6/asyncio/futures.py", line 334, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/discovery.py", line 164, in async_load_platform
    hass, component, hass_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 49, in async_setup_component
    return (yield from setup_tasks[domain])
  File "/usr/lib/python3.6/asyncio/futures.py", line 334, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 60, in async_setup_component
    return (yield from task)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 159, in _async_setup_component
    conf_util.async_process_component_config(hass, config, domain)
  File "/usr/lib/python3.6/site-packages/homeassistant/config.py", line 622, in async_process_component_config
    platform = get_platform(domain, p_name)
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 104, in get_platform
    return get_component(PLATFORM_FORMAT.format(domain, platform))
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/sensor/hue.py", line 249
    return self.bridge.set_group(light_id, command)
                                                  ^
SyntaxError: 'return' outside function
2018-01-09 23:36:57 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/discovery.py", line 164, in async_load_platform
    hass, component, hass_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 49, in async_setup_component
    return (yield from setup_tasks[domain])
  File "/usr/lib/python3.6/asyncio/futures.py", line 334, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/discovery.py", line 164, in async_load_platform
    hass, component, hass_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 49, in async_setup_component
    return (yield from setup_tasks[domain])
  File "/usr/lib/python3.6/asyncio/futures.py", line 334, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 60, in async_setup_component
    return (yield from task)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 159, in _async_setup_component
    conf_util.async_process_component_config(hass, config, domain)
  File "/usr/lib/python3.6/site-packages/homeassistant/config.py", line 622, in async_process_component_config
    platform = get_platform(domain, p_name)
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 104, in get_platform
    return get_component(PLATFORM_FORMAT.format(domain, platform))
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/sensor/hue.py", line 249
    return self.bridge.set_group(light_id, command)
                                                  ^
SyntaxError: 'return' outside function
2018-01-09 23:36:57 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/discovery.py", line 164, in async_load_platform
    hass, component, hass_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 49, in async_setup_component
    return (yield from setup_tasks[domain])
  File "/usr/lib/python3.6/asyncio/futures.py", line 334, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/discovery.py", line 164, in async_load_platform
    hass, component, hass_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 49, in async_setup_component
    return (yield from setup_tasks[domain])
  File "/usr/lib/python3.6/asyncio/futures.py", line 334, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 60, in async_setup_component
    return (yield from task)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 159, in _async_setup_component
    conf_util.async_process_component_config(hass, config, domain)
  File "/usr/lib/python3.6/site-packages/homeassistant/config.py", line 622, in async_process_component_config
    platform = get_platform(domain, p_name)
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 104, in get_platform
    return get_component(PLATFORM_FORMAT.format(domain, platform))
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/sensor/hue.py", line 249
    return self.bridge.set_group(light_id, command)
                                                  ^
SyntaxError: 'return' outside function

Hope thats enough info

**Comment by robmarkcole** [comment]
Hi, please can you add:

1. HA version
2. Branch info (master or dev-phue)

Cheers

**Comment by GarmFighter** [comment]
0.60.1 and dev-phue
Have had the exact same problem on 0.60 and master too...
And for some strange reason when i add platform: hue my netatmo weatherstation is nowhere to be found.

**Comment by robmarkcole** [comment]
Your traceback refers to:
```
self.bridge.set_group
```
Which is actually [in the hue component](https://github.com/home-assistant/home-assistant/blob/8267a21bfe74520c7c8e0a8e94114476106261d9/homeassistant/components/hue.py#L242), so I think the issue lies there and is probably particular to your setup. I suggest you open an issue there. Cheers

**Comment by GarmFighter** [comment]
Ok, thanks...
I leave this open for now...?

**Comment by jimbob1001** [comment]
Did you download the latest version of hue.py from the dev-phue repo to your custom_components directory? There was a change to the original version of hue.py in 0.60.1 that needed updating for the sensors component to work again.

**Comment by robmarkcole** [comment]
Please bring your HA install and this custom component up to date, and reopen if any issue
