### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by marthoc** [robmarkcole/Hue-sensors-HASS#9]
I've started seeing this error pop up in my logs; when it is happening the temperature aspect of the motion sensor does not update. A restart of Home Assistant fixes it until it happens again. Any thoughts?
```
2017-10-25 16:16:48 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hue_motion_sensor_motion_1 fails
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 309, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/hue.py", line 91, in update
    self._data.update()
  File "/usr/src/app/homeassistant/util/__init__.py", line 306, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/sensor/hue.py", line 51, in update
    self.data = self.parse_hue_api_response(response.json())
  File "/config/deps/lib/python3.6/site-packages/hue_sensors.py", line 52, in parse_hue_api_response
    data_dict[_key] = parse_sml(sensor)
  File "/config/deps/lib/python3.6/site-packages/hue_sensors.py", line 74, in parse_sml
    data = {'temperature': response['state']['temperature']/100.0}
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by robmarkcole** [comment]
HI @marthoc it appears the sensor is returning `NoneType` for `temperature`, can you check what is being returned by the API?

**Comment by robmarkcole** [comment]
@marthoc ping

**Comment by robmarkcole** [comment]
This is moving to https://github.com/robmarkcole/Hue-sensors/issues/4
