### ISSUE TITLE
Error while setting up platform hue

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#98]
In 0.9
```
2018-12-31 07:01:45 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform hue
Traceback (most recent call last):
  File "/Users/robincole/Documents/Github/home-assistant/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/Users/robincole/anaconda3/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/Users/robincole/.homeassistant/custom_components/sensor/hue.py", line 148, in async_setup_platform
    await data.async_update_info()
  File "/Users/robincole/.homeassistant/custom_components/sensor/hue.py", line 167, in async_update_info
    for bridge in self.hass.data[hue.DOMAIN].values()
  File "/Users/robincole/.homeassistant/custom_components/sensor/hue.py", line 168, in <listcomp>
    if bridge.api is not None
AttributeError: 'collections.OrderedDict' object has no attribute 'api'
```

**Comment by robmarkcole** [comment]
`hass.data[hue.DOMAIN].values()` is returning `dict_values([OrderedDict([('host', '192.168.1.64'), ('filename', 'phue.conf'), ('allow_hue_groups', True), ('allow_unreachable', False)]), <homeassistant.components.hue.bridge.HueBridge object at 0x109866278>])` so we are not access the bridge object correctly?

**Comment by robmarkcole** [comment]
Should be fixed in https://github.com/robmarkcole/Hue-sensors-HASS/commit/0146b882e6ae05946c5974368826b910f1af3dec
